### PR TITLE
Add EPEL Repo

### PR DESCRIPTION
**Pull request by swadeley**
Add older python2-psutil for use in errata tests

Required for: https://github.com/SatelliteQE/robottelo/pull/8639

### CODE REVIEW

**Review by jameerpathan111 — APPROVED** [review]
Ack

**Review by jyejare — CHANGES_REQUESTED** [review]
Missing repos metadata.

**Comment by swadeley** [comment]
@jyejare I created the repo to hold one package, which I am just using to create need for an erratum, so I am not really using the repo itself for testing.

**Comment by swadeley** [comment]
Thank you

**Pull request merged**
