### PR TITLE
Replace yum3 repo

### PR DESCRIPTION
**Pull request by swadeley**
Hello

The packages in this fake_yum3 repo were incorrectly made (c. 2012). 

Unfortunately, the packages in this repo were all created with the incorrect release version format:
https://github.com/SatelliteQE/fedorapeople-repos/pull/6#issuecomment-721066566

So I cannot fix them, we have to replace them to get errata enumeration to work.

### CODE REVIEW

**Comment by swadeley** [comment]
Hello

This is the test that needed this repo to work for errata enumeration:

[ Test chost errata pagination #8173 ](https://github.com/SatelliteQE/robottelo/pull/8173)

**Comment by swadeley** [comment]
Hello

I previously explained which tests use the yum3 repo: https://github.com/SatelliteQE/fedorapeople-repos/pull/6#issuecomment-712757780

I will run some of those, but before that I need to update and test:


    +FAKE_3_ERRATA_ID = 'RHEA-2012:3733'  # for FAKE_3_YUM_REPO
    +FAKE_3_YUM_ERRATUM_COUNT = 28
used in:
`tests/foreman/api/test_errata.py -k test_positive_list`

--------------------------------------------------------------------------------------------------------------------------------

     +FAKE_3_YUM_REPOS_COUNT = 78
used in:
`tests/foreman/api/test_contentmanagement.py   -k test_positive_on_demand_sync`

**Comment by swadeley** [comment]
robottelo]$ pytest tests/foreman/api/test_errata.py -k test_positive_list
================================== test session starts ========================================
platform linux -- Python 3.8.6, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo_2/robottelo, inifile: pytest.ini
plugins: ibutsu-1.12, mock-3.3.1, forked-1.3.0, services-2.2.1, cov-2.10.1, xdist-1.34.0
collecting ... 2020-11-24 11:44:47 - conftest - DEBUG - Collected 14 test cases
collected 14 items / 12 deselected / 2 selected                                                                  

tests/foreman/api/test_errata.py ..                                                                        [100%]


============================ 2 passed, 12 deselected, 2 warnings in 232.88s (0:03:52) =====================

**Comment by swadeley** [comment]
robottelo]$  pytest --show-capture=no tests/foreman/cli/test_repository.py -k test_positive_create_with_yum_repo
================================== test session starts ========================================
platform linux -- Python 3.8.6, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo_2/robottelo, inifile: pytest.ini
plugins: ibutsu-1.12, mock-3.3.1, forked-1.3.0, services-2.2.1, cov-2.10.1, xdist-1.34.0
collecting ... 2020-11-24 11:41:59 - conftest - DEBUG - Collected 95 test cases
collected 95 items / 94 deselected / 1 selected                                                                  

tests/foreman/cli/test_repository.py .                                                                     [100%]

============================ 1 passed, 94 deselected, 2 warnings in 66.47s (0:01:06) =====================

**Review by mirekdlugosz — APPROVED** [review]
ACK, I used another copy of these changes to test https://github.com/SatelliteQE/robottelo/pull/8173 .

**Comment by mshriver** [comment]
This PR has been deployed internally.

**Comment by swadeley** [comment]
Thank you

**Pull request merged**
